DROP TABLE IF EXISTS incomes CASCADE;
CREATE TABLE incomes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  account_id INTEGER REFERENCES accounts(id) ON DELETE CASCADE,
  description VARCHAR(255) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  amount INTEGER NOT NULL,
  notes VARCHAR(255)
); 